arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # TODO(destogl): why is this interpreted as string???
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
